<?php
declare(strict_types=1);

/**
 * Generate a download manifest or curl script from a list of MAST product
 * URIs. Only official mast: archive URIs are accepted — this endpoint is
 * deliberately NOT a general-purpose URL proxy.
 *
 * POST JSON body:
 *   { "format": "txt" | "sh", "items": [ { "uri": "mast:...", "filename": "..." } ] }
 */
require_once __DIR__ . '/bootstrap.php';

oaj_rate_limit();

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'POST') {
    Response::error('METHOD_NOT_ALLOWED', 'Use POST with a JSON body.', 405);
}

$raw = (string) file_get_contents('php://input');
if (strlen($raw) > 200000) {
    Response::error('BAD_REQUEST', 'Request body is too large.', 413);
}
$body = json_decode($raw, true);
if (!is_array($body)) {
    Response::error('BAD_REQUEST', 'Body must be valid JSON.', 400);
}

$format = (string) ($body['format'] ?? 'txt');
if (!in_array($format, ['txt', 'sh'], true)) {
    Response::error('BAD_REQUEST', 'format must be txt or sh.', 400);
}

$items = $body['items'] ?? [];
if (!is_array($items) || count($items) === 0) {
    Response::error('BAD_REQUEST', 'items must be a non-empty array.', 400);
}
if (count($items) > 200) {
    Response::error('BAD_REQUEST', 'A maximum of 200 files can be included in one manifest.', 400);
}

$lines = [];
$clean = [];
foreach ($items as $item) {
    if (!is_array($item)) {
        continue;
    }
    $uri = (string) ($item['uri'] ?? '');
    $filename = basename((string) ($item['filename'] ?? 'download'));
    if (!preg_match('/^mast:(HST|JWST)\/product\/[A-Za-z0-9._\-\/]+$/', $uri)) {
        Response::error('BAD_REQUEST', 'Only official MAST archive URIs (mast:HST/… or mast:JWST/…) are allowed.', 400);
    }
    $url = MastClient::downloadUrl($uri);
    $clean[] = ['uri' => $uri, 'filename' => $filename, 'url' => $url];
    if ($format === 'sh') {
        $lines[] = 'curl -fL --retry 2 -o ' . escapeshellarg($filename) . ' ' . escapeshellarg($url);
    } else {
        $lines[] = $url . '  # ' . $filename;
    }
}

if (count($clean) === 0) {
    Response::error('BAD_REQUEST', 'No valid items supplied.', 400);
}

if ($format === 'sh') {
    array_unshift(
        $lines,
        '#!/usr/bin/env bash',
        '# Hubble/JWST download script generated by Our Astro Journey.',
        '# Files download directly from the official STScI MAST archive.',
        'set -euo pipefail',
        ''
    );
}

Response::ok([
    'query' => ['format' => $format, 'count' => count($clean)],
    'items' => $clean,
    'script' => implode("\n", $lines) . "\n",
]);
